### ISSUE TITLE
Inventory management casestudy

### ISSUE THREAD

**Issue by hyunjimoon** [Data4DM/BayesSD#17]
The end goal of this model are three:
- online decision
- dynamic timestep aggregation
- dynamic subscript aggregation

The first casestudy is the fusion of Bayequentist from DailyDigest and ManageChain from MonthlyModel. Three Bayesian checks are applied to chained system where demand/supply and material/information are matched. This is the diagram:

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/30194633/190862134-03296a9b-debc-420a-b91e-09d2cc891e15.png">

I aim to address first two topics from https://github.com/Data4DM/BayesSD/discussions/5, 
<div type='discussions-op-text'>

<sup>Originally posted by **hyunjimoon** September 12, 2022</sup>
## Goal
to figure out the best way to tune the following hyper-parameters and its useful resource. I left the link for each discussion (#12, #7, #9, #11) as they need active development, so please leave comment in each link! If you think of any other **tunable parmameters**, please leave a comment so that I can allocate a new discussion thread for that.

### 1. Typify model into PA or PAD based on the research purpose in https://github.com/Data4DM/BayesSD/discussions/12
- [Some models are useful, but how do we know which ones?Towards a unified Bayesian model taxonomy](https://arxiv.org/pdf/2209.02439.pdf)

### 2. Typify parameters to assumed or assumed time-series or estimated for testing in https://github.com/Data4DM/BayesSD/discussions/7 
- [this](https://statmodeling.stat.columbia.edu/2013/01/05/understanding-regression-models-and-regression-coefficients/#comment-125256) discussion on holding constant (clamping) between two leaders (Andrew Gelman and Judea Pearl)

**Comment by hyunjimoon** [comment]
@tomfid the following are analysis code and vensim file readied for the above goal. Ready to go!
- analysis using Stan engine: [this](https://github.com/Data4DM/BayesSD/blob/master/ContinuousCode/5_BayesCalib/prey-predator.ipynb) notebook with underlying codes via commit de6016150c48ade40f65432d2005701711ec870a
- vensim file: [chain_draws2data](https://github.com/Data4DM/BayesSD/blob/master/MonthlyModel/10%20mng(chain%20%E2%9B%93)/chain_draws2data.mdl) and [chain_data2draws2decison2data](https://github.com/Data4DM/BayesSD/blob/master/MonthlyModel/10%20mng(chain%20%E2%9B%93)/chain_data2draws2decison2data.mdl)

**Comment by hyunjimoon** [comment]
First fit success with this model!
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/30194633/192610991-c8464e75-cc76-444e-b4da-0a7a4c1bb0b5.png">

**Comment by hyunjimoon** [comment]
true dist:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/30194633/192614179-9e242cf2-99d9-462d-939f-159ab4b5bd6c.png">

**Comment by hyunjimoon** [comment]
Digging into dimension of `prior_pred`, `post_draws` in https://github.com/Data4DM/BayesSD/discussions/23#discussion-4429295

**Comment by hyunjimoon** [comment]
I need help in using driving data using vensim's lookup function structure.

**Comment by tomfid** [comment]
In other words, using lookups as a container for data? I wouldn't normally do that, unless I wanted random access to the data, or was planning to export to some other tool that couldn't digest Vensim data variables.

One possible strategy is to create placeholder lookups with generic values, then populate them at runtime with a .cin file (perhaps generated in Excel) containing the real values. This won't work if the goal is to export the .mdl though. In that case, with a little finagling, you could just generate the lookups in mdl syntax and paste them into the equation listing.

**Comment by tomfid** [comment]
There are two forms in mdl syntax:

https://www.vensim.com/documentation/lookups.html

LOOKUP NAME([(Xmin, Ymin)-(Xmax, Ymax),(Xref1, Yref1),(Xref2,Yref2),...(Xrefn,Yrefn)]

(X1, Y1), (X2,Y2), . . .(Xn, Yn) )
~	Units ~ Description  |

The stuff in [ ] can be omitted.

or:

LOOKUP NAME( X1, X2, X3,....Xn, Y1, Y2, Y3,....Yn)
~	Units ~ Description |

**Comment by tomfid** [comment]
.cin syntax is the same - just make sure it's all on one line, and omit the ~ and stuff after.

**Comment by hyunjimoon** [comment]
This attempt to use lookup function started from digging into how pysd is using external data via initializing the model with `.initialize(data_file = .tab)`. https://github.com/SDXorg/pysd/discussions/371

**Comment by hyunjimoon** [comment]
1. need @Hazhir's input on how to incorporate hierarchical modeling with testing framework to make the test result less path dependent? Should we start from no pooling or complete pooling? https://github.com/Data4DM/BayesSD/issues/34

2. ran `draws2data` for inventorymanagement after transforming two flow rates (`production start rate`, `production rate`) into stocks by adding process noise then generated 

## 3. new paper on SBC which I wish to reboot with the name behavior test
a. Paper introduce "Theory and Practice of Choosing Test Quantities for SBC" 

b. suggested behavior test as SBC's new name (mail below)

c. customized prior and resolution i.e. polynomial function approximation of prior distribution based on user input CDF (current grant i.e. probability distributions are not made for priors) and setting time step for desired resolution are two problem needs to be solved. From algorithm in https://github.com/Data4DM/BayesSD/discussions/11 for pattern classification for reference modes, `segment` is the key but setting it is vague https://github.com/Data4DM/BayesSD/discussions/19 i.e. importance of hyperparameter; the same problem in simulation-based test.
<img width="830" alt="image" src="https://user-images.githubusercontent.com/30194633/193901889-67fc7a68-99a9-484e-bb02-b21ff33100df.png">

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/30194633/193901614-02f9a27f-79e2-4828-b1bd-240264540f88.png">

d. simulation-based test's goal is inferential behavioral of model over an ensemble of possible assumptions and observations

e. modelers are giving stimulus to test organism (model)'s response (behavior := actions and mannerisms made by individuals, organisms, systems in some environment. ...  computed response of the system or organism to various stimuli or inputs)

f. how to herald the part underneath? Assumed part of the model (e.g. approximator's Hessian matrix, level of hierarchy (gardens of forking path; we see what we expect to see), hyperparameter or hyperprior) that should be tested

<img width="916" alt="image" src="https://user-images.githubusercontent.com/30194633/193885135-2aee9bb4-c0e1-472b-95e6-09da5d4e2ac2.png">

**Comment by hyunjimoon** [comment]
- tracing spikes and negative values
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/30194633/194551152-6e102347-f412-4680-a402-533c2a2473b1.png">

**Comment by hyunjimoon** [comment]
First `data2draws` success that takes 24 mins!
```
04:49:46 - cmdstanpy - INFO - CmdStan start processing
chain 1 |          | 00:00 Status
chain 2 |          | 00:00 Status

chain 3 |          | 00:00 Status


chain 4 |          | 00:00 Status
chain 1 |▍         | 00:02 Status

chain 3 |▍         | 00:04 Status

chain 3 |▉         | 00:20 Iteration:    1 / 2000 [  0%]  (Warmup)

chain 3 |█▎        | 00:37 Iteration:  100 / 2000 [  5%]  (Warmup)
chain 2 |▉         | 00:46 Iteration:    1 / 2000 [  0%]  (Warmup)

chain 3 |█▊        | 00:54 Iteration:  200 / 2000 [ 10%]  (Warmup)

chain 3 |██▎       | 01:09 Iteration:  300 / 2000 [ 15%]  (Warmup)

chain 3 |██▋       | 01:24 Iteration:  400 / 2000 [ 20%]  (Warmup)

chain 3 |███▏      | 01:40 Iteration:  500 / 2000 [ 25%]  (Warmup)

chain 3 |███▋      | 01:54 Iteration:  600 / 2000 [ 30%]  (Warmup)

chain 3 |████      | 02:08 Iteration:  700 / 2000 [ 35%]  (Warmup)

chain 3 |████▌     | 02:23 Iteration:  800 / 2000 [ 40%]  (Warmup)

chain 3 |█████     | 02:38 Iteration:  900 / 2000 [ 45%]  (Warmup)

chain 3 |█████▉    | 02:54 Iteration: 1001 / 2000 [ 50%]  (Sampling)

chain 3 |██████▎   | 03:09 Iteration: 1100 / 2000 [ 55%]  (Sampling)

chain 3 |██████▊   | 03:24 Iteration: 1200 / 2000 [ 60%]  (Sampling)

chain 1 |▉         | 03:46 Iteration:    1 / 2000 [  0%]  (Warmup)

chain 3 |███████▋  | 03:55 Iteration: 1400 / 2000 [ 70%]  (Sampling)

chain 3 |████████▏ | 04:10 Iteration: 1500 / 2000 [ 75%]  (Sampling)

chain 3 |████████▋ | 04:24 Iteration: 1600 / 2000 [ 80%]  (Sampling)

chain 3 |█████████ | 04:40 Iteration: 1700 / 2000 [ 85%]  (Sampling)

chain 3 |█████████▌| 04:54 Iteration: 1800 / 2000 [ 90%]  (Sampling)

chain 3 |██████████| 05:09 Iteration: 1900 / 2000 [ 95%]  (Sampling)
chain 2 |█▎        | 07:34 Iteration:  100 / 2000 [  5%]  (Warmup)


chain 4 |▍         | 20:12 Status


chain 4 |▉         | 20:22 Iteration:    1 / 2000 [  0%]  (Warmup)


chain 4 |█▎        | 20:36 Iteration:  100 / 2000 [  5%]  (Warmup)


chain 4 |█▊        | 20:48 Iteration:  200 / 2000 [ 10%]  (Warmup)


chain 1 |█▎        | 21:09 Iteration:  100 / 2000 [  5%]  (Warmup)


chain 4 |██▋       | 21:13 Iteration:  400 / 2000 [ 20%]  (Warmup)


chain 4 |███▏      | 21:24 Iteration:  500 / 2000 [ 25%]  (Warmup)


chain 4 |███▋      | 21:37 Iteration:  600 / 2000 [ 30%]  (Warmup)


chain 4 |████      | 21:49 Iteration:  700 / 2000 [ 35%]  (Warmup)


chain 4 |████▌     | 22:00 Iteration:  800 / 2000 [ 40%]  (Warmup)


chain 4 |█████     | 22:12 Iteration:  900 / 2000 [ 45%]  (Warmup)


chain 4 |█████▉    | 22:25 Iteration: 1001 / 2000 [ 50%]  (Sampling)


chain 4 |██████▎   | 22:38 Iteration: 1100 / 2000 [ 55%]  (Sampling)


chain 4 |██████▊   | 22:51 Iteration: 1200 / 2000 [ 60%]  (Sampling)


chain 4 |███████▎  | 23:03 Iteration: 1300 / 2000 [ 65%]  (Sampling)


chain 4 |███████▋  | 23:16 Iteration: 1400 / 2000 [ 70%]  (Sampling)


chain 4 |████████▏ | 23:28 Iteration: 1500 / 2000 [ 75%]  (Sampling)


chain 4 |████████▋ | 23:41 Iteration: 1600 / 2000 [ 80%]  (Sampling)


chain 4 |█████████ | 23:53 Iteration: 1700 / 2000 [ 85%]  (Sampling)


chain 4 |█████████▌| 24:05 Iteration: 1800 / 2000 [ 90%]  (Sampling)


chain 4 |██████████| 24:18 Iteration: 1900 / 2000 [ 95%]  (Sampling)04:49:46 - cmdstanpy - INFO - CmdStan start processing
chain 1 |          | 00:00 Status
chain 2 |          | 00:00 Status

chain 3 |          | 00:00 Status


chain 4 |          | 00:00 Status
chain 1 |▍         | 00:02 Status

chain 3 |▍         | 00:04 Status

chain 3 |▉         | 00:20 Iteration:    1 / 2000 [  0%]  (Warmup)

chain 3 |█▎        | 00:37 Iteration:  100 / 2000 [  5%]  (Warmup)
chain 2 |▉         | 00:46 Iteration:    1 / 2000 [  0%]  (Warmup)

chain 3 |█▊        | 00:54 Iteration:  200 / 2000 [ 10%]  (Warmup)

chain 3 |██▎       | 01:09 Iteration:  300 / 2000 [ 15%]  (Warmup)

chain 3 |██▋       | 01:24 Iteration:  400 / 2000 [ 20%]  (Warmup)

chain 3 |███▏      | 01:40 Iteration:  500 / 2000 [ 25%]  (Warmup)

chain 3 |███▋      | 01:54 Iteration:  600 / 2000 [ 30%]  (Warmup)

chain 3 |████      | 02:08 Iteration:  700 / 2000 [ 35%]  (Warmup)

chain 3 |████▌     | 02:23 Iteration:  800 / 2000 [ 40%]  (Warmup)

chain 3 |█████     | 02:38 Iteration:  900 / 2000 [ 45%]  (Warmup)

chain 3 |█████▉    | 02:54 Iteration: 1001 / 2000 [ 50%]  (Sampling)

chain 3 |██████▎   | 03:09 Iteration: 1100 / 2000 [ 55%]  (Sampling)

chain 3 |██████▊   | 03:24 Iteration: 1200 / 2000 [ 60%]  (Sampling)

chain 1 |▉         | 03:46 Iteration:    1 / 2000 [  0%]  (Warmup)

chain 3 |███████▋  | 03:55 Iteration: 1400 / 2000 [ 70%]  (Sampling)

chain 3 |████████▏ | 04:10 Iteration: 1500 / 2000 [ 75%]  (Sampling)

chain 3 |████████▋ | 04:24 Iteration: 1600 / 2000 [ 80%]  (Sampling)

chain 3 |█████████ | 04:40 Iteration: 1700 / 2000 [ 85%]  (Sampling)

chain 3 |█████████▌| 04:54 Iteration: 1800 / 2000 [ 90%]  (Sampling)

chain 3 |██████████| 05:09 Iteration: 1900 / 2000 [ 95%]  (Sampling)
chain 2 |█▎        | 07:34 Iteration:  100 / 2000 [  5%]  (Warmup)


chain 4 |▍         | 20:12 Status


chain 4 |▉         | 20:22 Iteration:    1 / 2000 [  0%]  (Warmup)


chain 4 |█▎        | 20:36 Iteration:  100 / 2000 [  5%]  (Warmup)


chain 4 |█▊        | 20:48 Iteration:  200 / 2000 [ 10%]  (Warmup)


chain 1 |█▎        | 21:09 Iteration:  100 / 2000 [  5%]  (Warmup)


chain 4 |██▋       | 21:13 Iteration:  400 / 2000 [ 20%]  (Warmup)


chain 4 |███▏      | 21:24 Iteration:  500 / 2000 [ 25%]  (Warmup)


chain 4 |███▋      | 21:37 Iteration:  600 / 2000 [ 30%]  (Warmup)


chain 4 |████      | 21:49 Iteration:  700 / 2000 [ 35%]  (Warmup)


chain 4 |████▌     | 22:00 Iteration:  800 / 2000 [ 40%]  (Warmup)


chain 4 |█████     | 22:12 Iteration:  900 / 2000 [ 45%]  (Warmup)


chain 4 |█████▉    | 22:25 Iteration: 1001 / 2000 [ 50%]  (Sampling)


chain 4 |██████▎   | 22:38 Iteration: 1100 / 2000 [ 55%]  (Sampling)


chain 4 |██████▊   | 22:51 Iteration: 1200 / 2000 [ 60%]  (Sampling)


chain 4 |███████▎  | 23:03 Iteration: 1300 / 2000 [ 65%]  (Sampling)


chain 4 |███████▋  | 23:16 Iteration: 1400 / 2000 [ 70%]  (Sampling)


chain 4 |████████▏ | 23:28 Iteration: 1500 / 2000 [ 75%]  (Sampling)


chain 4 |████████▋ | 23:41 Iteration: 1600 / 2000 [ 80%]  (Sampling)


chain 4 |█████████ | 23:53 Iteration: 1700 / 2000 [ 85%]  (Sampling)


chain 4 |█████████▌| 24:05 Iteration: 1800 / 2000 [ 90%]  (Sampling)


chain 4 |██████████| 24:18 Iteration: 1900 / 2000 [ 95%]  (Sampling)
```

**Comment by hyunjimoon** [comment]
Because of the implementational restriction of stochasticity, we are enforcing time-varying concepts in vensim?

1. $\theta \sim N(3, .4)$
2. random variable
- driving data: 2, 3, 2, 3,...
comparing the probability of our implemented / numerically computed result.

Y_0
Y_1, Y_2
Predictive distirbution, or the p of realized data from the assumed model is greater when we assume homogeneity across time and heterogeneity across space.
P(Y_0|M) < P(.5(Y_1 + Y_2)|M)

**Comment by hyunjimoon** [comment]
Filtering is before ergodic or stationary or where time hetereogenity is not settled yet
\theta_t-1 =0.5
\theta_{t} =? generates samples from prior (sampled from a prior distribution = N(\theta_t-1 , 1)

p(D|\theta_t1) + p(D|\theta_t2) + p(D|\theta_t3) + p(D|\theta_t4)

**Comment by hyunjimoon** [comment]
@tomfid I am following your comment on using reference throughput. Thanks. However, I faced the following active initial error and I am not sure about its cause. Especially I don't follow how `Process noise std norm data` can be initialized in two different ways (leading to unmatched initial and active). 
<img width="774" alt="image" src="https://user-images.githubusercontent.com/30194633/196418747-3e52bd7b-3754-4f02-8cf6-d815a622fd0b.png">

**Comment by hyunjimoon** [comment]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/30194633/196509172-918e1e22-b20f-4b9b-a38d-a9f1ef84bcfe.png">
- shadow structure success
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/30194633/196511757-d69ae257-4fef-433f-9efa-f2d21790d9a2.png">

- reference initial stock
